#! /usr/bin/python
# Joseph Ernest, 2016/11/12

import sys, daemon, time, os

class usbdeaddaemon(daemon.Daemon):
	def regen(self): # генерация списка (используеться срез начиная с айди)
		os.system("./"+str(sys.argv[0])+" stop")
		usb_devices = list(os.popen("lsusb").read().split("\n")) #
		usb_devices.pop() #
		for i in range(len(usb_devices)): # вырезаем лишнее
			device = usb_devices[i]
			usb_devices[i] = device[20:]
		with open('dev.list', 'w') as f: # сохраняем в файл
			for i in usb_devices:
				f.write(str(i)+"\n")
			print("dev.list created!")
	def run (self): # функция запуска скрипта
		with open('dev.list', 'r') as f: # читаем из файла доверенные устройства
			usb_devices_old = list(f.read().split("\n"))
			usb_devices_old.pop()
			while True:
				usb_devices = list(os.popen("lsusb").read().split("\n"))
				usb_devices.pop()
				for i in range(len(usb_devices)):
					device = usb_devices[i]
					usb_devices[i] = device[20:]
					
				count1 = 0
				for i in usb_devices_old:
					for j in usb_devices:
						if i == j:
							count1 += 1
				
				count2 = 0
				for i in usb_devices:
					for j in usb_devices_old:
						if i == j:
							count2 += 1
							
	
				if (count1 != len(usb_devices_old)) and (sys.argv[1] == "startext" or sys.argv[1] == "startall"): # сверяем со списком ожидаемых иначе тревога
					os.system("powerroff") #------------------------ команда которая выполнится
					break
				
				if (count2 != len(usb_devices)) and (sys.argv[1] == "startcon" or sys.argv[1] == "startall"): # сверяем со списком ожидаемых иначе тревога
					os.system("poweroff") #------------------------ команда которая выполнится
					break
				time.sleep(1)
				
	def quit(self):
		pass
	def upt(self):
		os.system("./"+str(sys.argv[0])+" stop")
		mode = input("plug device and enter start mode (default: None)\n> ")
		new_devices = list(os.popen("lsusb").read().split("\n")) #
		new_devices.pop() #
		for i in range(len(new_devices)): # вырезаем лишнее
			device = new_devices[i]
			new_devices[i] = device[20:]
		try:
			with open('dev.list', 'r') as f: # читаем из файла доверенные устройства
				usb_devices_old = list(f.read().split("\n"))
				usb_devices_old.pop()
				
			all_devices = set(list(usb_devices_old + new_devices)) # получаем уникальные устр
			with open('dev.list', 'w') as f: # сохраняем в файл
				for i in all_devices:
					f.write(str(i)+"\n")
		except FileNotFoundError:
			with open('dev.list', 'w') as f: # сохраняем в файл
				for i in new_devices:
					f.write(str(i)+"\n")
		if mode == "startcon" or mode =="startext" or mode == "startall":
			os.system("./"+str(sys.argv[0])+" "+str(mode))
			print(f"dev.list updated and service ruing {mode} mode!")
		else:
			print("dev.list updated! service not runing")

daemon = usbdeaddaemon()

if 'startcon' == sys.argv[1]: 
	daemon.start()
if 'startext' == sys.argv[1]: 
	daemon.start()
if 'startall' == sys.argv[1]: 
	daemon.start()
elif 'stop' == sys.argv[1]: 
	daemon.stop()
elif 'restart' == sys.argv[1]: 
	daemon.restart()
elif "upt" == sys.argv[1]:
	daemon.upt()
elif "regen" == sys.argv[1]:
	daemon.regen()
